# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.3/service.json

apiVersion: v1
kind: Service
metadata:
  name: rustfs-svc
spec:
  selector:
    app: rustfs
  ports:
    - name: api
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: ui
      protocol: TCP
      port: 9001
      targetPort: 9001
